mod bayonetta;
mod brave;
mod buddy;
mod captain;
mod chrom;
mod cloud;
mod daisy;
mod dedede;
mod demon;
mod diddy;
mod dolly;
mod donkey;
mod duckhunt;
mod edge;
mod eflame;
mod elight;
mod falco;
mod fox;
mod gamewatch;
mod ganon;
mod gaogaen;
mod gekkouga;
mod ike;
mod inkling; 
mod jack;
mod kamui;
mod ken;
mod kirby;
mod koopa;
mod koopajr;
mod krool;
mod link;
mod littlemac;
mod lucario;
mod lucas;
mod lucina;
mod luigi;
mod mario;
mod mariod;
mod marth;
mod master;
mod metaknight;
mod mewtwo;
mod miifighter;
mod miigunner;
mod miiswordsman;
mod murabito;
mod ness;
mod packun;
mod pacman;
mod palutena;
mod peach;
mod pichu;
mod pikachu;
mod pikmin;
mod pit;
mod pitb;
mod popo;
mod ptrainer;
mod purin;
mod reflet;
mod richter;
mod ridley;
mod robot;
mod rockman;
mod rosetta;
mod roy;
mod ryu;
mod samus;
mod samusd;
mod sheik;
mod shizue;
mod shulk;
mod simon;
mod snake;
mod sonic;
mod szerosuit;
mod tantan;
mod toonlink;
mod trail;
mod wario;
mod wiifit;
mod wolf;
mod younglink;
mod yoshi;
mod zelda;

pub fn install() {
    bayonetta::install();
    brave::install();
    buddy::install();
    captain::install();
    chrom::install();
    cloud::install();
    daisy::install();
    dedede::install();
    demon::install();
    diddy::install();
    dolly::install();
    donkey::install();
    duckhunt::install();
    edge::install();
    eflame::install();
    elight::install();
    falco::install();
    fox::install();
    gamewatch::install();
    ganon::install();
    gaogaen::install();
    gekkouga::install();
    ike::install();
    inkling::install(); 
    jack::install();
    kamui::install();
    ken::install();
    kirby::install();
    koopa::install();
    koopajr::install();
    krool::install();
    link::install();
    littlemac::install();
    lucario::install();
    lucas::install();
    lucina::install();
    luigi::install();
    mario::install();
    mariod::install();
    marth::install();
    master::install();
    metaknight::install();
    mewtwo::install();
    miifighter::install();
    miigunner::install();
    miiswordsman::install();
    murabito::install();
    ness::install();
    packun::install();
    pacman::install();
    palutena::install();
    peach::install();
    pichu::install();
    pikachu::install();
    pikmin::install();
    pit::install();
    pitb::install();
    popo::install();
    ptrainer::install();
    purin::install();
    reflet::install();
    richter::install();
    ridley::install();
    robot::install();
    rockman::install();
    rosetta::install();
    roy::install();
    ryu::install();
    samus::install();
    samusd::install();
    sheik::install();
    shizue::install();
    shulk::install();
    simon::install();
    snake::install();
    sonic::install();
    szerosuit::install();
    tantan::install();
    toonlink::install();
    trail::install();
    wario::install();
    wiifit::install();
    wolf::install();
    younglink::install();
    yoshi::install();
    zelda::install();
}